import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Content-Type': 'text/plain',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const projectSlug = url.searchParams.get('project');
    const orgSlug = url.searchParams.get('org');

    if (!projectSlug || !orgSlug) {
      return new Response('# Default llms.txt\nAllow: /\nNo-Train: *', { headers: corsHeaders });
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Fetch project settings
    const { data: org } = await supabase
      .from('organizations')
      .select('id, slug')
      .eq('slug', orgSlug)
      .single();

    if (!org) {
      return new Response('# Organization not found\nDisallow: *', { headers: corsHeaders });
    }

    const { data: project } = await supabase
      .from('projects')
      .select('id, slug, allow_llm_training, allow_llm_crawlers, allow_llm_summarization, visibility, is_published')
      .eq('organization_id', org.id)
      .eq('slug', projectSlug)
      .single();

    if (!project) {
      return new Response('# Project not found\nDisallow: *', { headers: corsHeaders });
    }

    // Generate llms.txt content
    let content = '# llms.txt - LLM Access Policy\n';
    content += `# Generated by Docspeare for project: ${projectSlug}\n`;
    content += `# Learn more: https://llmstxt.org/\n\n`;

    // If project is not public or not published, disallow everything
    if (project.visibility !== 'public' || !project.is_published) {
      content += '# This project is not public\n';
      content += 'Disallow: *\n';
      content += 'No-Train: *\n';
      content += 'No-Summarize: *\n';
      return new Response(content, { headers: corsHeaders });
    }

    // Allow reading published pages
    content += '# Content access\n';
    content += 'Allow: /docs/\n';
    content += 'Disallow: /internal/\n';
    content += 'Disallow: /drafts/\n\n';

    // Training permissions
    content += '# Training permissions\n';
    if (project.allow_llm_training) {
      content += 'Train: /docs/\n';
    } else {
      content += 'No-Train: *\n';
    }
    content += '\n';

    // Summarization permissions
    content += '# Summarization permissions\n';
    if (project.allow_llm_summarization) {
      content += 'Summarize: /docs/\n';
    } else {
      content += 'No-Summarize: *\n';
    }
    content += '\n';

    // Specific crawler permissions
    const allowedCrawlers = project.allow_llm_crawlers || [];
    if (allowedCrawlers.length > 0) {
      content += '# Allowed LLM crawlers\n';
      for (const crawler of allowedCrawlers) {
        if (crawler && crawler.trim()) {
          content += `Allow-Crawler: ${crawler}\n`;
        }
      }
    } else {
      content += '# Crawler access\n';
      content += 'Allow-Crawler: *\n';
    }

    console.log(`Generated llms.txt for ${orgSlug}/${projectSlug}`);
    return new Response(content, { headers: corsHeaders });

  } catch (error) {
    console.error('Error generating llms.txt:', error);
    return new Response('# Error generating llms.txt\nDisallow: *\nNo-Train: *', { headers: corsHeaders });
  }
});
