import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Content-Type': 'text/plain',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const projectSlug = url.searchParams.get('project');
    const orgSlug = url.searchParams.get('org');

    if (!projectSlug || !orgSlug) {
      return new Response('# Default robots.txt\nUser-agent: *\nAllow: /', { headers: corsHeaders });
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Fetch project settings
    const { data: org } = await supabase
      .from('organizations')
      .select('id, slug')
      .eq('slug', orgSlug)
      .single();

    if (!org) {
      return new Response('# Organization not found\nUser-agent: *\nDisallow: /', { headers: corsHeaders });
    }

    const { data: project } = await supabase
      .from('projects')
      .select('id, slug, allow_indexing, disallowed_paths, visibility, is_published')
      .eq('organization_id', org.id)
      .eq('slug', projectSlug)
      .single();

    if (!project) {
      return new Response('# Project not found\nUser-agent: *\nDisallow: /', { headers: corsHeaders });
    }

    // Generate robots.txt content
    let content = '# robots.txt generated by DocLayer\n';
    content += `# Project: ${projectSlug}\n\n`;
    content += 'User-agent: *\n';

    // If project is not public or not published, disallow everything
    if (project.visibility !== 'public' || !project.is_published) {
      content += 'Disallow: /\n';
      return new Response(content, { headers: corsHeaders });
    }

    // Handle indexing setting
    if (!project.allow_indexing) {
      content += 'Disallow: /\n';
    } else {
      content += 'Allow: /\n';
      
      // Add disallowed paths
      const disallowedPaths = project.disallowed_paths || [];
      
      // Always disallow drafts and internal
      content += 'Disallow: /drafts/\n';
      content += 'Disallow: /internal/\n';
      
      for (const path of disallowedPaths) {
        if (path && path.trim()) {
          content += `Disallow: ${path.startsWith('/') ? path : '/' + path}\n`;
        }
      }
    }

    // Add sitemap reference
    content += `\n# Sitemap\nSitemap: https://${orgSlug}.example.com/docs/${projectSlug}/sitemap.xml\n`;

    console.log(`Generated robots.txt for ${orgSlug}/${projectSlug}`);
    return new Response(content, { headers: corsHeaders });

  } catch (error) {
    console.error('Error generating robots.txt:', error);
    return new Response('# Error generating robots.txt\nUser-agent: *\nAllow: /', { headers: corsHeaders });
  }
});
