// This file is automatically generated. Do not edit it directly.
import { createClient, type Session, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    // Disable auto-refresh to avoid hammering the refresh endpoint (429s).
    // We refresh manually via ensureFreshSession.
    autoRefreshToken: false,
    // Prevent multiple tabs from racing refreshes.
    multiTab: false,
  }
});

// Extra guard: stop any auto-refresh timers that may still be running.
supabase.auth.stopAutoRefresh();

// Hard guard: wrap refreshSession so even internal callers (if any) are throttled.
// This prevents rapid-fire refresh attempts that can trigger 429 and sign-outs.
const REFRESH_COOLDOWN_KEY = "sb_refresh_cooldown_until";
const REFRESH_COOLDOWN_MS = 2 * 60 * 1000;

const originalRefreshSession = supabase.auth.refreshSession.bind(supabase.auth) as SupabaseClient<Database>["auth"]["refreshSession"];
let refreshInFlight: ReturnType<typeof originalRefreshSession> | null = null;
let lastRefreshAt = 0;

supabase.auth.refreshSession = async (currentSession?: Session | null) => {
  const now = Date.now();
  const cooldownUntil = Number(localStorage.getItem(REFRESH_COOLDOWN_KEY) || "0");

  // If we're in a cooldown window, skip refreshing.
  if (cooldownUntil && now < cooldownUntil) {
    const { data } = await supabase.auth.getSession();
    return { data, error: null };
  }

  // Deduplicate concurrent refresh attempts.
  if (refreshInFlight) return refreshInFlight;

  // Basic minimum gap between refresh attempts.
  if (lastRefreshAt && now - lastRefreshAt < 30_000) {
    const { data } = await supabase.auth.getSession();
    return { data, error: null };
  }

  refreshInFlight = originalRefreshSession(currentSession);

  try {
    const result = await refreshInFlight;
    lastRefreshAt = Date.now();

    if (result.error && (result.error as any)?.status === 429) {
      localStorage.setItem(REFRESH_COOLDOWN_KEY, String(Date.now() + REFRESH_COOLDOWN_MS));
    } else {
      localStorage.removeItem(REFRESH_COOLDOWN_KEY);
    }

    return result;
  } finally {
    refreshInFlight = null;
  }
};
